### ISSUE TITLE
BadZipFile error for some replays

### ISSUE THREAD

**Issue by Kaszanas** [Kaszanas/SC2_Datasets#18]
This needs to be looked into.

```
ERROR:root:zipfile error was raised
Traceback (most recent call last):
  File "f:\Projects\SC2EGSet_Experiments\src\dataset\utils\zip_utils.py", line 31, in unpack_zipfile
    zip_file.extract(member, path_to_extract)
  File "C:\Users\kasza\.pyenv\pyenv-win\versions\3.10.2\lib\zipfile.py", line 1617, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Users\kasza\.pyenv\pyenv-win\versions\3.10.2\lib\zipfile.py", line 1689, in _extract_member        
    shutil.copyfileobj(source, target)
  File "C:\Users\kasza\.pyenv\pyenv-win\versions\3.10.2\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\kasza\.pyenv\pyenv-win\versions\3.10.2\lib\zipfile.py", line 923, in read
    data = self._read1(n)
  File "C:\Users\kasza\.pyenv\pyenv-win\versions\3.10.2\lib\zipfile.py", line 1013, in _read1
    self._update_crc(data)
  File "C:\Users\kasza\.pyenv\pyenv-win\versions\3.10.2\lib\zipfile.py", line 941, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file '138403fd434342459b7382639a222b91.SC2Replay.json'
```

**Comment by Kaszanas** [comment]
This never came back again. I am closing this. I think this was fixed.
